export const QUESTIONS = [
    {
        id: "age",
        label: "1. Age",
        description: "What is your current age?",
        type: "number",
        placeholder: "e.g. 25",
    },
    {
        id: "employmentStability",
        label: "2. Employment Stability",
        description: "How long have you been in your current job or source of income?",
        type: "radio",
        options: ["<6 months", "6–12 months", "1–3 years", "3–5 years", ">5 years"],
    },
    {
        id: "monthlyIncome",
        label: "3. Monthly Income",
        description: "What is your average monthly income (after tax)?",
        type: "number",
        placeholder: "e.g. 50000",
    },
    {
        id: "numBankAccounts",
        label: "4. Bank Accounts",
        description: "How many active bank accounts do you have?",
        type: "number",
        placeholder: "e.g. 2",
    },
    {
        id: "numCreditCards",
        label: "5. Active Loans / Credit Cards",
        description: "How many active loans or credit cards do you currently have?",
        type: "number",
        placeholder: "e.g. 1",
    },
    {
        id: "interestRate",
        label: "6. Avg. Loan Interest Rate (%)",
        description: "What is the average interest rate on your current loans? (If none, enter 0)",
        type: "number",
        placeholder: "e.g. 12",
    },
    {
        id: "outstandingDebt",
        label: "7. Total Outstanding Debt",
        description: "What is the total amount you currently owe across all loans?",
        type: "number",
        placeholder: "e.g. 150000",
    },
    {
        id: "monthlyEmis",
        label: "8. Total Monthly EMIs",
        description: "How much do you pay in total loan installments every month?",
        type: "number",
        placeholder: "e.g. 5000",
    },
    {
        id: "incomeStability",
        label: "9. Income Stability",
        description: "Is your income fixed or does it vary month to month?",
        type: "radio",
        options: ["Fixed", "Slightly variable", "Highly variable"],
    },
    {
        id: "savingsBuffer",
        label: "10. Savings & Emergency Buffer",
        description: "How many months of expenses do you currently have saved?",
        type: "radio",
        options: ["None", "<1 month", "1–3 months", "3–6 months", ">6 months"],
    },
    {
        id: "expenseRatio",
        label: "11. Monthly Expense Ratio",
        description: "How much of your income do you spend every month (approx.)?",
        type: "radio",
        options: ["<40%", "40–60%", "60–75%", ">75%"],
    },
    {
        id: "pastLoanExperience",
        label: "12. Past Loan Experience",
        description: "Have you ever taken a loan before? If yes, did you repay it on time?",
        type: "radio",
        options: [
            "Never taken",
            "Taken & repaid early/on time",
            "Taken & repaid late",
            "Taken & defaulted",
        ],
    },
    {
        id: "digitalBehavior",
        label: "13. Digital Behavior",
        description: "How often do you pay bills (phone, electricity, rent) before their due date?",
        type: "radio",
        options: ["Always early", "On time", "Sometimes late", "Usually late"],
    },
    {
        id: "dependents",
        label: "14. Dependents",
        description: "How many people depend financially on you?",
        type: "radio",
        options: ["None", "1", "2–3", "more"],
    },
    {
        id: "educationLevel",
        label: "15. Education Level",
        description: "What is your highest education completed?",
        type: "radio",
        options: ["No formal education", "High school", "UG", "PG", "Professional degree"],
    },
    {
        id: "financialDiscipline",
        label: "16. Financial Discipline",
        description: "Do you track your monthly expenses or maintain a budget?",
        type: "radio",
        options: ["Yes, strictly", "Yes, loosely", "No"],
    },
];
